kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basicimport
  namespace: trident
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic
